#!/bin/sh

TMP=tmp.html

OUT=`echo $1 | sed -e 's/.md/.html/'`
cat template.head > $TMP
markdown $1 >> $TMP
cat template.tail >> $TMP
#assuming js-beautify/html-beautify exists
html-beautify -n $TMP > $OUT

rm $TMP
