#!/bin/sh

MKDWN=$1.md
OUT=$1.html
TMP=tmp.html

cat template.head > $TMP
markdown $MKDWN >> $TMP
cat template.tail >> $TMP

#assuming js-beautify/html-beautify exists
html-beautify -tn $TMP > $OUT

rm $TMP
